# xstr ='0123456789'
xstr = input("input some string:")
print("a:", xstr[2])
print("b:", xstr[-2])
print("c:", xstr[0:5])
print("d:", xstr[0:-2])
print("e:", xstr[2::2])
print("f:", xstr[1::2])
print("g:", xstr[::-1])
print("h:", xstr[-1::-2])
print("i:", len(xstr))
