# xstr ='0123456789'
xstr =input("input some string:")
print(type(xstr))
print(xstr[2])
print(xstr[-2])
print(xstr[0:5])
print(xstr[0:-2])
print(xstr[2::2])
print(xstr[1::2])
print(xstr[::-1])
print(xstr[-1::-2])
print(len(xstr))
